//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookPublication
    {
        public int Book_ID { get; set; }
        public string Publisher_Local_Int { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ISBAN { get; set; }
        public string TitleOfBook { get; set; }
        public Nullable<int> Author_ID { get; set; }
        public Nullable<int> DepartID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
